name:  Docker IMage
on:
  push:
    branche:["main"]
jobs:

build:
  runs-on: ubuntu-latest

  Steps:
  -uses: actions/checkout@v4
  -name: Login Dockerhub

  env: 
    DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
    DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

  run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

-name: build the docker image
run: docker buil -t  SampleWebAPP


-name : push to Dockerhub
  
